# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kyma_poc',
                'doc_host': 'https://jwmatthews.github.io',
                'git_url': 'https://github.com/jwmatthews/kyma_poc',
                'lib_path': 'kyma_poc'},
  'syms': {'kyma_poc.core': {'kyma_poc.core.foo': ('core.html#foo', 'kyma_poc/core.py')}}}
