# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['template', 'prompt', 'model', 'chain']

# %% ../nbs/00_core.ipynb 3
from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate, SystemMessagePromptTemplate, HumanMessagePromptTemplate
from langchain.schema.output_parser import StrOutputParser
from langchain_experimental.utilities.python import PythonREPL


def _sanitize_output(text: str):
    _, after = text.split("```python")
    return after.split("```")[0]

template = """Write some python code to solve the user's problem. 

Return only python code in Markdown format, e.g.:

```python
....
```"""
prompt = ChatPromptTemplate.from_messages(
    [("system", template), ("human", "{input}")]
)

model = ChatOpenAI()

chain = prompt | model | StrOutputParser() | _sanitize_output | PythonREPL().run

