# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_report.ipynb.

# %% auto 0
__all__ = ['Report']

# %% ../nbs/04_report.ipynb 3
import yaml 

class Report:
    def __init__(self, path_to_report):
        self.path_to_report = path_to_report
        self.report = None 

    def get_report(self):
        if self.report is None:
            self.report = self._read_report()  
        return self.report

    def _reformat_report(self, report):
        new_report = {}
        # Reformat from a List to a Dict where the key is the name
        for item in report:
            if "violations" in item.keys():
                print(f"v = {item['violations']}")
                # Drop entries that lack Violations
                new_report[item['name']] = item
        return new_report
    
    def _read_report(self):
        with open(self.path_to_report, 'r') as f:
            report = yaml.safe_load(f)
        report = self._reformat_report(report)
        return report
     
