name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required libraries for the project
        shell: bash -l {0}
        run: |
          echo "Using following Python environment:"
          which pip
          which python
          pip install -r requirements.txt
          pip install -e .
      - uses: fastai/workflows/quarto-ghp@master
